### ISSUE TITLE
[Question] What's the menu on the left?

### ISSUE THREAD

**Issue by spidersouris** [lexcast/snowfall#1]
Hey!

Sorry for asking a question here which isn't related to your package, even if It's pretty cool.

I'd just like to know what package is the menu on the left of your screenshot. Could you please give me its GitHub Repo or its https://atom.io/packages link, please?

Also, I noticed a typo in the README.md file: Settingss > Settings

Have a great day!

**Comment by lexcast** [comment]
The package is https://atom.io/packages/tool-bar with the https://atom.io/packages/flex-tool-bar plugin.

The typo is fixed now, thank you.
