### ISSUE TITLE
Pause snowfall when Atom is not in the foreground

### ISSUE THREAD

**Issue by winstliu** [lexcast/snowfall#2]
Because we won't be able to appreciate the snow falling anyway.  It should also save a few hours of battery life when I have multiple Atom windows open :).

**Comment by lexcast** [comment]
Hi @50Wliu, nice suggestion.
Is there an Atom method to know if the windows is in the foreground? I think I can use blur/focus events

**Comment by winstliu** [comment]
I think you can use [`atom.getCurrentWindow()`](https://atom.io/docs/api/v1.22.1/AtomEnvironment#instance-getCurrentWindow)[`.isVisible()`](https://electronjs.org/docs/api/browser-window#winisvisible) (or alternatively, [`.isFocused()`](https://electronjs.org/docs/api/browser-window#winisfocused)).

**Comment by winstliu** [comment]
Seems fixed to me.
